export interface IMaterialDeExames {
    nome?: String;
    ativo?: Boolean;
    npo?: Boolean;
    jejum?: Boolean;
    exigePreparo?: Boolean;
    exigeDieta?: Boolean;
    informaNumeroDeColetas?: Boolean;
    geraItemDeSolicitacao?: Boolean;
    exigeIntervaloDeColeta?: Boolean;
    exigeRegiaoAnatomica?: Boolean;
    ingestaoDeMedicamento?: Boolean;
    dependenteDeExame?: Boolean;
    analisadoPelaCII?: Boolean;
    interesseDaCOMEDI?: Boolean;
    exigeImpressao?: Boolean;
    apareceResultado?: Boolean;
    contaCelulas?: Boolean;
    limiteDeSolicitacao?: Boolean;
    formaDeRespiracao?: Boolean;
    automatico?: Boolean;
    exigeDadosComplementares?: Boolean;
    natureza?: String;
    sumario?: String;
    tempoJejum?: Number;
    intervaloMinimo?: Number;
    unidadeDeTempo?: String;
    validade?: Number;
    agendamentoMinimo?: Number;
    tempoLimiteDaSolicitacao?: Number;
    unidadeDeTempoDaSolicitacao?: String;
    numeroDeAmostras?: Number;
    numeroDeAmostrasPadrao?: Number;
    diasLimiteDefault?: Number;
    tempoLimiteDefault?: Number;
    numeroDeAmostrarPorIntervalo?: Number;
    tempoLimiteDeAmostraPorIntervalo?: Number;
    unidadeLimiteDeTempoDoPeriodo?: String;
    permiteSolicitacaoPosAlta?: Boolean;
    tempoPermitidoParaSolicitarPosAlta?: Number;
    tempoPermitidoParaSolicitarPosAltaPelasAreasExecutoras?: Number;
    cartaDeColeta?: String;
    laboratoriaTercerizado?: Boolean;
    naoCancelaExamaAposAlta?: Boolean;
    materialId?: Number;
    materialNome?: String;

}

export class MaterialDeExames implements IMaterialDeExames {
    public nome?: String;
    public ativo?: Boolean;
    public npo?: Boolean;
    public jejum?: Boolean;
    public exigePreparo?: Boolean;
    public exigeDieta?: Boolean;
    public informaNumeroDeColetas?: Boolean;
    public geraItemDeSolicitacao?: Boolean;
    public exigeIntervaloDeColeta?: Boolean;
    public exigeRegiaoAnatomica?: Boolean;
    public ingestaoDeMedicamento?: Boolean;
    public dependenteDeExame?: Boolean;
    public analisadoPelaCII?: Boolean;
    public interesseDaCOMEDI?: Boolean;
    public exigeImpressao?: Boolean;
    public apareceResultado?: Boolean;
    public contaCelulas?: Boolean;
    public limiteDeSolicitacao?: Boolean;
    public formaDeRespiracao?: Boolean;
    public automatico?: Boolean;
    public exigeDadosComplementares?: Boolean;
    public natureza?: String;
    public sumario?: String;
    public tempoJejum?: Number;
    public intervaloMinimo?: Number;
    public unidadeDeTempo?: String;
    public validade?: Number;
    public agendamentoMinimo?: Number;
    public tempoLimiteDaSolicitacao?: Number;
    public unidadeDeTempoDaSolicitacao?: String;
    public numeroDeAmostras?: Number;
    public numeroDeAmostrasPadrao?: Number;
    public diasLimiteDefault?: Number;
    public tempoLimiteDefault?: Number;
    public numeroDeAmostrarPorIntervalo?: Number;
    public tempoLimiteDeAmostraPorIntervalo?: Number;
    public unidadeLimiteDeTempoDoPeriodo?: String;
    public permiteSolicitacaoPosAlta?: Boolean;
    public tempoPermitidoParaSolicitarPosAlta?: Number;
    public tempoPermitidoParaSolicitarPosAltaPelasAreasExecutoras?: Number;
    public cartaDeColeta?: String;
    public laboratoriaTercerizado?: Boolean;
    public naoCancelaExamaAposAlta?: Boolean;
    public materialId?: Number;
    public materialNome?: String;
}
