version: '2'
services:
  pacientes-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/pacientes/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pacientes
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5435:5432
