dependencies:
  - name: common
    version: 1.2.1
    repository: 'http://element.basis.com.br/repository/commons-helm/'
  - name: postgresql
    version: 8.6.1
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: postgresql.install
  - name: elasticsearch
    version: 1.32.4
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: elasticsearch.install