madrecliente:
  name: cliente
  image:
    repository: basis-registry.basis.com.br/madre/cliente
    tag: latest
  ingress:
    url: "madre.tst.basis.com.br"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
    tls:
    - hosts:
      - madre.tst.basis.com.br
      secretName: madretst-cert
  ports:
    port: 80
  proxy:
    locations:
    - pacientes
    - internacao
    - prescricao
    - farmacia
    - suprimentos

gateway:
  name: gateway
  image: 
    repository: basis-registry.basis.com.br/madre/madregateway
    tag: latest
  ports:
    port: 8080
  configmap:
      datasource:
        url: jdbc:postgresql://pgsql-madre/madre
        username: madre
        password: madre

pacientes:
  name: pacientes
  image:
    repository: basis-registry.basis.com.br/madre/madrepacientes
    tag: latest
  ports:
    port: 8081
  configmap:
    spring:
      data:
        jest:
          uri: http://elasticsearch-client.elasticsearch:9200
      elasticsearch: 
        rest:
          uris: http://elasticsearch-client.elasticsearch:9200
      datasource:
        url: jdbc:postgresql://pgsql-madre/madre
        username: madre
        password: madre

prescricao:
  name: prescricao
  image:
    repository: basis-registry.basis.com.br/madre/madreprescricao
    tag: latest
  ports:
    port: 8081
  configmap:
    spring:
      data:
        jest:
          uri: http://elasticsearch-client.elasticsearch:9200
      elasticsearch: 
        rest:
          uris: http://elasticsearch-client.elasticsearch:9200
      datasource:
        url: jdbc:postgresql://pgsql-madre/madre
        username: madre
        password: madre

farmacia:
  name: farmacia
  image:
    repository: basis-registry.basis.com.br/madre/madrefarmacia
    tag: latest
  ports:
    port: 8081
  configmap:
    spring:
      data:
        jest:
          uri: http://elasticsearch-client.elasticsearch:9200
      elasticsearch: 
        rest:
          uris: http://elasticsearch-client.elasticsearch:9200
      datasource:
        url: jdbc:postgresql://pgsql-madre/madre
        username: madre
        password: madre

internacao:
  name: internacao
  image:
    repository: basis-registry.basis.com.br/madre/madreinternacao
    tag: latest
  ports:
    port: 8081
  configmap:
    spring:
      data:
        jest:
          uri: http://elasticsearch-client.elasticsearch:9200
      elasticsearch: 
        rest:
          uris: http://elasticsearch-client.elasticsearch:9200
      datasource:
        url: jdbc:postgresql://pgsql-madre/madre
        username: madre
        password: madre

suprimentos:
  name: suprimentos
  image:
    repository: basis-registry.basis.com.br/madre/madresuprimentos
    tag: latest
  ports:
    port: 8081
  configmap:
    spring:
      data:
        jest:
          uri: http://elasticsearch-client.elasticsearch:9200
      elasticsearch:
        rest:
          uris: http://elasticsearch-client.elasticsearch:9200
      datasource:
        url: jdbc:postgresql://pgsql-madre/madre
        username: madre
        password: madre

comum:
  imagePullSecrets:
  - name: basis-registry

postgresql:
  install: true
  fullnameOverride: pgsql-madre
  postgresqlUsername: madre
  postgresqlPassword: madre
  postgresqlDatabase: madre
  postgresqlPostgresPassword: basis123
  persistence:
    storageClass: nfs-kube-des
    size: 10Gi

