madrecliente:
  name: cliente
  image:
    repository: basis-registry.basis.com.br/madre/cliente
    tag: latest
  ingress:
    url: "madre.tst.basis.com.br"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
    tls:
      - hosts:
          - madre.tst.basis.com.br
        secretName: madretst-cert
  ports:
    port: 80
  proxy:
    locations:
    - pacientes
    - internacao
    - prescricao
    - farmacia
    - suprimentos
    - madreconsulta

gateway:
  name: gateway
  image:
    repository: basis-registry.basis.com.br/madre/madregateway
    tag: latest
  imagePullSecrets:
    - name: basis-registry
  ports:
    port: 8080
  configmap:
    spring:
      profiles:
        active: prod,swagger

pacientes:
  name: pacientes
  image:
    repository: basis-registry.basis.com.br/madre/madrepacientes
    tag: latest
  ports:
    port: 8081
  configmap:
    spring:
      datasource:
        url: jdbc:postgresql://pgsql-madre/madre
        username: pacientes
        password: pacientes

prescricao:
  name: prescricao
  image:
    repository: basis-registry.basis.com.br/madre/madreprescricao
    tag: latest
  ports:
    port: 8081
  configmap:
    spring:
      datasource:
        url: jdbc:postgresql://pgsql-madre/madre
        username: prescricao
        password: prescricao

farmacia:
  name: farmacia
  image:
    repository: basis-registry.basis.com.br/madre/madrefarmacia
    tag: latest
  ports:
    port: 8081
  configmap:
    spring:
      datasource:
        url: jdbc:postgresql://pgsql-madre/madre
        username: farmacia
        password: farmacia

internacao:
  name: internacao
  image:
    repository: basis-registry.basis.com.br/madre/madreinternacao
    tag: latest
  ports:
    port: 8081
  configmap:
    spring:
      datasource:
        url: jdbc:postgresql://pgsql-madre/madre
        username: internacao
        password: internacao

madresuprimentos:
  name: madresuprimentos
  image:
    repository: basis-registry.basis.com.br/madre/madresuprimentos
    tag: latest
  ports:
    port: 8081
  jdk: 11
  configmap:
    spring:
      datasource:
        url: jdbc:postgresql://pgsql-madre/madre
        username: suprimentos
        password: suprimentos

madreconsulta:
  name: madreconsulta
  image:
    repository: basis-registry.basis.com.br/madre/madreconsulta
    tag: latest
  ports:
    port: 8081
  configmap:
    spring:
      datasource:
        url: jdbc:postgresql://pgsql-madre/madre
        username: consulta
        password: consulta

comum:
  imagePullSecrets:
    - name: basis-registry
  configmap:
    spring:
      profiles:
        active: prod,swagger
      data:
        jest:
          uri: http://elasticsearch-client.elasticsearch:9200
      elasticsearch:
        rest:
          uris: http://elasticsearch-client.elasticsearch:9200
      kafka:
        bootstrap-servers: confluent-cp-kafka.confluent:9092

postgresql:
  install: true
  fullnameOverride: pgsql-madre
  postgresqlUsername: madre
  postgresqlPassword: madre
  postgresqlDatabase: madre
  postgresqlPostgresPassword: basis123
  persistence:
    storageClass: nfs-kube-des
    size: 10Gi
