version: '2'
services:
  prescricao-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/prescricao/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=prescricao
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
