version: '2'
services:
  madreseguranca-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.13
#   volumes:
 #    - ~/volumes/jhipster/madreseguranca/elasticsearch/:/usr/share/elasticsearch/data/
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      - 'discovery.type=single-node'
      - 'cluster.routing.allocation.disk.threshold_enabled=false'
