version: '2'
services:
  madreseguranca-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/madreseguranca/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=madreseguranca
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5439:5432
