version: '2'
services:
  madresuprimentos-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/madresuprimentos/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=madresuprimentos
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5437:5432
